### ISSUE TITLE
Upgrade container fails when node is running on Alpine

### ISSUE THREAD

**Issue by cerebrate** [rancher/system-upgrade-controller#109]
**Version**
0.6.2

**Platform/Architecture**
linux-amd64

**Describe the bug**
When a k3s node is running under Alpine Linux, the upgrade containers invoked by system-upgrade-controller fail.

**To Reproduce**
1. Install k3s on a fresh Alpine Linux node.
2. Allow system-upgrade-controller to run its initial job on that node.

**Expected behavior**
The upgrade pod/job to run to successful completion.

**Actual behavior**
The upgrade container in the relevant job failed, with the following error:

```
+ upgrade
+ get_k3s_process_info
[INFO]  K3S binary is running with pid 3579
3581
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver)'
+ awk '{print $1}'
+ K3S_PID='3579
3581'
+ '[' -z '35793581' ]
+ info 'K3S binary is running with pid 3579
3581'
+ echo '[INFO] ' 'K3S binary is running with pid 3579
+ awk '{print $1}'
+ K3S_PID='3579
3581'+ '[' -z '35793581' ]
+ info 'K3S binary is running with pid 3579
3581'
+ echo '[INFO] ' 'K3S binary is running with pid 3579
3581'
+ cat /host/proc/3579 3581/cmdline
cat: read error: Is a directory
cat: can't open '3581/cmdline': No such file or directory
+ awk '{print $1}'
+ head -n 1
+ K3S_BIN_PATH=+ '[' '3579
3581' '==' 1 ]
+ '[' -z  ]
+ fatal 'Failed to fetch the k3s binary path from process 3579
3581'
+ echo '[ERROR] ' 'Failed to fetch the k3s binary path from process 3579
3581'
[ERROR]  Failed to fetch the k3s binary path from process 3579
3581
+ exit 1
```

**Comment by cerebrate** [comment]
This is fixable by altering

`grep -E -v '(init|grep|channelserver)'`

to

`grep -E -v '(init|grep|channelserver|supervise-daemon)'`

but I can't seem to track down where to submit a PR for the upgrade containers?

**Comment by ntx-ben** [comment]
@cerebrate this is currently in PR at https://github.com/k3s-io/k3s-upgrade/pull/26

**Comment by dweomer** [comment]
Closing this since k3s-io/k3s-upgrade#26 is merged.
