### ISSUE TITLE
system-upgrade-controller: failed to create job for host with long hostname

### ISSUE THREAD

**Issue by brlbil** [rancher/system-upgrade-controller#110]
**Version**
v0.6.2

**Platform/Architecture**
linux-amd64

**Describe the bug**
For certain hostnames, the controller fails to create the update job. Because `metadata.name` becomes an invalid value, means the job name does not match the regex used for validation the name, `'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'`

**To Reproduce**
Enable upgrade on a host that has the hostname like this `abc-ddddddd-eeeeeee.ff.gg.hhhhhhhh.net` and the plan name `test-update`

**Expected behavior**
The controller shortens the hostname for the job name, so the controller should make sure of the validity of the name before creating the job.

**Actual behavior**
Though it is very rare for some nodes upgrade fails.

**Additional context**
The error message is below, seems like since the controller cuts the name in the wrong place so name ends with a `.`

```
E0113 21:56:56.415121       1 controller.go:135] error syncing 'k3os-system/test-update': handler system-upgrade-controller: failed to create k3os-system/apply-test-update-on-abc-ddddddd-eeeeeee.ff.gg.hhhhhhhh.-c7942 batch/v1, Kind=Job for system-upgrade-controller k3os-system/test-update: Job.batch "apply-test-update-on-abc-ddddddd-eeeeeee.ff.gg.hhhhhhhh.-c7942" is invalid: metadata.name: Invalid value: "apply-test-update-on-abc-ddddddd-eeeeeee.ff.gg.hhhhhhhh.-c7942": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing
```

**Comment by dweomer** [comment]
Fixed by #113
