### ISSUE TITLE
The built-in K3S upgrade in Rancher is stuck,No error log

### ISSUE THREAD

**Issue by yl-yue** [rancher/system-upgrade-controller#111]
**Issue describe**
The built-in K3S upgrade in Rancher is stuck,No error log.

I have explained the details here: https://github.com/rancher/rancher/issues/31971

Other than the meaningless hints in the Rancher UI, I couldn't find any useful error messages in the relevant upgrade components

**Comment by dweomer** [comment]
The rancher issue should be sufficient.
