### ISSUE TITLE
Upgrade job is timing out

### ISSUE THREAD

**Issue by kaosmonk** [rancher/system-upgrade-controller#115]
**Version**
v0.6.2

**Platform/Architecture**
Centos 8, rke2 v1.20.5+rke2r1

**Describe the bug**
Update job is being created but it doesn't seem to work; no error is seen except that the msg "Job was active longer than specified deadline" is being logged

**To Reproduce**
Take what's outlined [here](https://docs.rke2.io/upgrade/automated_upgrade/) as a basic example I am also testing with.

**Expected behavior**
Job manages to upgrade the rke2 binary

**Actual behavior**
I'm trying to bump rke2 to v1.20.6+rke2r1 but it's not happening for me. A pod `apply-agent-plan-on-ip-...` is created but it ends up being in a pending state without an obvious error

Any ideas please let me know and thanks in advance.

**Comment by dweomer** [comment]
If you could share your `kubectl describe` output and the plan manifest that you are using that would be helpful I think. Additionally, `kubectl get node --show-labels` output.

**Comment by kaosmonk** [comment]
Ah, I have had several misconfigured bits hence it was timing out, thanks for reaching out tho!
