### ISSUE TITLE
Generated node affinity uses cloud-provider hostname instead of k8s hostname

### ISSUE THREAD

**Issue by marcusianlevine** [rancher/system-upgrade-controller#119]
**Version**

`v0.6.2`

**Describe the bug**
When deployed in an RKE cluster managed by Rancher Server, which is affected by [this issue with overriding cloud-provider hostnames](https://github.com/rancher/rancher/issues/18070), the SUC incorrectly generates the `nodeAffinity` for the `kubernetes.io/hostname` label, using the cloud-provider hostname even if it has been overridden within k8s. 

For example, in my shop we do not include our local domain `x-y-z` in our node's hostnames, but since our nodes run in an AWS VPC, the result of `$(curl -s 169.254.169.254/latest/meta-data/local-hostname)` does include the `x-y-z.example.com` domain.

Apparently the SUC reads from this cloud-provider source rather than the k8s API itself, so the resulting node affinities do not match any node, resulting in an unschedulable pod.

EDIT: for clarity, here is the (anonymized) contents of the `Addresses` section of `kubectl describe node x.y.z`
```
Addresses:
  InternalIP:   x.y.z
  Hostname:     ip-x-y-z
  InternalDNS:  ip-x-y-z.example.com
```

**To Reproduce**
1. Deploy an RKE-managed cluster from Rancher Server, using nodes in a cloud provider VPC
2. Locally configure the nodes to have a hostname without the fully-qualified domain present in the official cloud-provider hostname
3. Deploy SUC and a Plan that targets some of the nodes

**Expected behavior**
Plan results in Pods that can actually be scheduled onto the targeted nodes

**Actual behavior**
Plan's resulting Pods have `nodeAffinities` that result in the Pod never being scheduled since they include the fully-qualified `x-y-z.example.com` hostname instead of the overridden hostname.

**Additional context**
Associated unresolved Rancher issue: https://github.com/rancher/rancher/issues/18070

UPDATE: noticed [this section](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#built-in-node-labels) in the k8s docs indicating that the `kubernetes.io/hostname` label is not a reliable means for detecting the node name - in some environments it may differ, so SUC cannot rely on the label to determine node affinities for each Pod.

**Comment by tulanian** [comment]
Just started looking at the SUC and am encountering the same/similar problem. I'm using terraform to deploy the cluster using launch templates and autoscaling groups in AWS--basically a custom cluster where the `docker run` is embedded into the launch template. According to the docs this should use `hostname -s` as the nodename, but a `kubectl get nodes` shows the FQDNs. The `kubernetes.io/hostname` label for each node, however, is non-FQDN. The SUC appears to assume that this label and the nodename are the same, but as also pointed out above, this label is unreliable.
