### ISSUE TITLE
Error E0801 in System Upgrade Controller Logs

### ISSUE THREAD

**Issue by darktempla** [rancher/system-upgrade-controller#125]
**Version**
v0.6.2

**Platform/Architecture**
linux-arm          - Rasbian Buster 10 (2 nodes)
linux-amd64     - Debian Buster 10  (1 node) 

**Describe the bug**
Errors in logs:
```bash
W0801 06:22:04.881598       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-08-01T06:22:05Z" level=info msg="Creating CRD plans.upgrade.cattle.io"
time="2021-08-01T06:22:05Z" level=info msg="Waiting for CRD plans.upgrade.cattle.io to become available"
time="2021-08-01T06:22:06Z" level=info msg="Waiting for CRD plans.upgrade.cattle.io to become available"
time="2021-08-01T06:22:07Z" level=info msg="Waiting for CRD plans.upgrade.cattle.io to become available"
time="2021-08-01T06:22:07Z" level=info msg="Waiting for CRD plans.upgrade.cattle.io to become available"
time="2021-08-01T06:22:08Z" level=info msg="Done waiting for CRD plans.upgrade.cattle.io to become available"
time="2021-08-01T06:22:08Z" level=info msg="Starting /v1, Kind=Node controller"
time="2021-08-01T06:22:08Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-08-01T06:22:08Z" level=info msg="Starting batch/v1, Kind=Job controller"
time="2021-08-01T06:22:08Z" level=info msg="Starting upgrade.cattle.io/v1, Kind=Plan controller"
E0801 07:39:28.569823       1 controller.go:135] error syncing 'system-upgrade/agent-plan': handler system-upgrade-controller: failed to update system-upgrade/apply-agent-plan-on-mac0-k3sn-with-1ec39e10294c503701dff7-cb1f8 batch/v1, Kind=Job for system-upgrade-controller system-upgrade/agent-plan: jobs.batch "apply-agent-plan-on-mac0-k3sn-with-1ec39e10294c503701dff7-cb1f8" not found, requeuing
E0801 08:25:42.214297       1 controller.go:135] error syncing 'system-upgrade/apply-server-plan-on-pi1-k3sm-with-1ec39e10294c503701dff7-b6a23': handler system-upgrade-controller: jobs.batch "apply-server-plan-on-pi1-k3sm-with-1ec39e10294c503701dff7-b6a23" not found, requeuing
E0801 08:28:30.494939       1 controller.go:135] error syncing 'system-upgrade/apply-agent-plan-on-mac0-k3sn-with-1ec39e10294c503701dff7-cb1f8': handler system-upgrade-controller: jobs.batch "apply-agent-plan-on-mac0-k3sn-with-1ec39e10294c503701dff7-cb1f8" not found, requeuing
E0801 08:43:31.320008       1 controller.go:135] error syncing 'system-upgrade/apply-agent-plan-on-pi2-k3sn-with-1ec39e10294c503701dff72-cbd36': handler system-upgrade-controller: jobs.batch "apply-agent-plan-on-pi2-k3sn-with-1ec39e10294c503701dff72-cbd36" not found, requeuing
```

**To Reproduce**
1. Install the system-upgrade-controller as per doco on cluster
```
kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.6.2/system-upgrade-controller.yaml
```
2. Create the following system upgrade plans

Master Plan:
```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
```
Agent Plan:
```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  channel: https://update.k3s.io/v1-release/channels/stable
```

3. View the logs in the system-upgrade-controller

**Expected behavior**
K3s nodes upgraded as expected
no errors in the logs.
status on objects and logs to clearly outline what has happened even if no update required.

**Actual behavior**

Error in logs as highlight above.
Documentation or searches on google that outline the process not real clear about expected status etc.

**Additional context**

Nodes:
```bash
$ kubectl get nodes
NAME        STATUS   ROLES                  AGE    VERSION
mac0-k3sn   Ready    <none>                 4d6h   v1.21.3+k3s1
pi2-k3sn    Ready    <none>                 5d     v1.21.3+k3s1
pi1-k3sm    Ready    control-plane,master   5d4h   v1.21.3+k3s1
```

Plans are in same namespaces as system-upgrade controller
```bash
$ kubectl get plans -A
NAMESPACE        NAME          AGE
system-upgrade   server-plan   3d23h
system-upgrade   agent-plan    3d23h
```
Status on plans:
```yaml
# Master Plan Status
status:
  conditions:
  - lastUpdateTime: "2021-08-05T12:20:17Z"
    reason: Channel
    status: "True"
    type: LatestResolved
  latestHash: 1ec39e10294c503701dff7288ae43d17d8c59e4cf96a89cc89ad1321
  latestVersion: v1.21.3-k3s1

# Agent Plan Status
status:
  conditions:
  - lastUpdateTime: "2021-08-05T12:28:30Z"
    reason: Channel
    status: "True"
    type: LatestResolved
  latestHash: 1ec39e10294c503701dff7288ae43d17d8c59e4cf96a89cc89ad1321
  latestVersion: v1.21.3-k3s1
```

**Comment by onedr0p** [comment]
I am on v0.7.4 and I am seeing my logs being spammed with similar messages. The behavior I am seeing on `watch kubectl get po -n system-upgrade` is that a pod keeps being created and immediately goes into a `Terminating` state.

```
system-upgrade-controller-85b5d9bcd5-9nq82 system-upgrade-controller time="2021-08-19T21:36:43Z" level=error msg="error syncing 'system-upgrade/apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c': handler system-upgrade-controller: jobs.batch \"apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c\" not found, requeuing"
system-upgrade-controller-85b5d9bcd5-9nq82 system-upgrade-controller time="2021-08-19T21:37:55Z" level=error msg="error syncing 'system-upgrade/apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c': handler system-upgrade-controller: jobs.batch \"apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c\" not found, requeuing"
```

**Comment by dweomer** [comment]
> I am on v0.7.4 and I am seeing my logs being spammed with similar messages. The behavior I am seeing on `watch kubectl get po -n system-upgrade` is that a pod keeps being created and immediately goes into a `Terminating` state.
> 
> ```
> system-upgrade-controller-85b5d9bcd5-9nq82 system-upgrade-controller time="2021-08-19T21:36:43Z" level=error msg="error syncing 'system-upgrade/apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c': handler system-upgrade-controller: jobs.batch \"apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c\" not found, requeuing"
> system-upgrade-controller-85b5d9bcd5-9nq82 system-upgrade-controller time="2021-08-19T21:37:55Z" level=error msg="error syncing 'system-upgrade/apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c': handler system-upgrade-controller: jobs.batch \"apply-k3s-server-on-k8s-0-with-57eb7803114642f8ff2061b7ae-de03c\" not found, requeuing"
> ```
> 
> I am also seeing teh status with duplicate nodes:
> 
> ```
> kubectl get plan/k3s-server -n system-upgrade -o yaml | grep k8s-0 | wc -l
> 4028
> ```
> 
> ```json
> ...
>     "status": {
>         "applying": [
>             "k8s-0",
>             "k8s-0",
>             "k8s-0",
>             "k8s-0",
>             "k8s-0",
>             "k8s-0",
>             "k8s-0",
> ...
>         ],
> ...
> ```
> 
> Plans:
> 
> * https://github.com/onedr0p/home-cluster/blob/58f1e5d3f4b3eafdd2722da34c4407d1d61d451f/cluster/apps/system-upgrade/system-upgrade-controller/agent-plan.yaml
> * https://github.com/onedr0p/home-cluster/blob/58f1e5d3f4b3eafdd2722da34c4407d1d61d451f/cluster/apps/system-upgrade/system-upgrade-controller/server-plan.yaml

@onedr0p please consider opening up a new issue (but linking to this one, due to similar log messages) as the duplicated entries you shared from your plan's `.status.applying` are concerning (and should not be happening). Given that I have not witnessed such behavior I will need some extra help reproducing this issue to be able to understand what is going on:
- what does your cluster setup look like?
  - how many control-plane nodes
  - how many worker nodes?
  - are you using a custom cloud provider?
- do you witness this behavior with earlier 0.7.x releases of SUC?

The log entries that you see I think are due to SUC attempting to de-dupe jobs (which with how wrangler object generation events works in a distributed system can still occur) compounded by the fact that your plan seems to already have multiple duplicate "applying" entries that result in jobs (these are essentially taken as-is by SUC). Before trying different versions of SUC, it might be worth attempting a correction: leverage `kubectl edit` to wipe out the `.status.applying` on any plan with duplicates.

**Comment by dweomer** [comment]
> **Expected behavior**
> K3s nodes upgraded as expected
> no errors in the logs.
> status on objects and logs to clearly outline what has happened even if no update required.
> 
> **Actual behavior**
> 
> Error in logs as highlight above.
> Documentation or searches on google that outline the process not real clear about expected status etc.

@darktempla thank you for submitting this! You do list "k3s nodes upgraded as expected" as an expected behavior but I do not see a "k3s nodes not upgraded" or similar listed for actual behavior. Did the upgrades succeed?

**Comment by dweomer** [comment]
> > **Expected behavior**
> > K3s nodes upgraded as expected
> > no errors in the logs.
> > status on objects and logs to clearly outline what has happened even if no update required.
> > **Actual behavior**
> > Error in logs as highlight above.
> > Documentation or searches on google that outline the process not real clear about expected status etc.
> 
> @darktempla thank you for submitting this! You do list "k3s nodes upgraded as expected" as an expected behavior but I do not see a "k3s nodes not upgraded" or similar listed for actual behavior. Did the upgrades succeed?

Nevermind. It turns out this is a separate issue, captured at https://github.com/rancher/rancher/issues/32050

**Comment by onedr0p** [comment]
Sorry for not following up, glad you found the issue!

**Comment by dweomer** [comment]
@darktempla this should happen a lot less often with the below fix(es). Please see https://github.com/rancher/system-upgrade-controller/issues/134#issuecomment-933734170:
> * [v0.7.7](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.7.7) (arrow_right [[backport release-0.7] job parallelism is zero unless in applying list #153](https://github.com/rancher/system-upgrade-controller/pull/153))
> * [v0.8.0](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.8.0) (arrow_right [job parallelism is zero unless in applying list #145](https://github.com/rancher/system-upgrade-controller/pull/145) )

**Comment by darktempla** [comment]
> @darktempla this should happen a lot less often with the below fix(es). Please see [#134 (comment)](https://github.com/rancher/system-upgrade-controller/issues/134#issuecomment-933734170):
> 
> > * [v0.7.7](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.7.7) (arrow_right [[backport release-0.7] job parallelism is zero unless in applying list #153](https://github.com/rancher/system-upgrade-controller/pull/153))
> > * [v0.8.0](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.8.0) (arrow_right [job parallelism is zero unless in applying list #145](https://github.com/rancher/system-upgrade-controller/pull/145) )

Thanks @dweomer - apologies for delayed reply been off the tools for a bit in my personal time. I will take the latest and greatest for a spin see if works as expected. Really like the idea of a cluster that upgrades itself so hoping to get it working :)
