### ISSUE TITLE
upgrades sometimes take longer than expected

### ISSUE THREAD

**Issue by dweomer** [rancher/system-upgrade-controller#134]
**Version**
`v0.6.1`+

**Platform/Architecture**
all

**Describe the bug**
It is not uncommon for upgrades to take an extra sync cycle or two to complete (15-30 minutes). I believe that this is due to aggressive reaping of jobs for nodes not in a `${plan}.status.applying` slice in conjunction with how jobs are generated via wrangler.

**To Reproduce**
Setup a cluster with some nodes, typically 3 or more and attempt an upgrade. It is not consistently reproducible but you will notice that upgrades can sometimes take up to 30+ minutes to complete.

**Expected behavior**
Upgrades jobs complete in a timely manner all the time, every time.

**Actual behavior**
Upgrades sometimes take an extra 15-30 minutes to complete.

**Additional context**
Related issues:
- https://github.com/rancher/system-upgrade-controller/issues/120
- https://github.com/rancher/system-upgrade-controller/issues/125
- https://github.com/k3s-io/k3s/issues/3007
- https://github.com/rancher/rancher/issues/32050#issuecomment-905976098
- https://github.com/rancher/rancher/issues/34494
- https://github.com/rancher/rancher/issues/34560#issuecomment-912043292

A hallmark of this bug is upgrade jobs without corresponding pods and kubelet events/errors that look like: 
![image](https://user-images.githubusercontent.com/1033444/132078840-6300327c-fa39-4713-ac1c-31cae7459c6e.png)

**Comment by snasovich** [comment]
@dweomer , is this one related as well or looks like something else at a glance? https://github.com/rancher/rancher/issues/34403#issuecomment-904188732

**Comment by dweomer** [comment]
Fixed:
- [v0.7.7](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.7.7) (:arrow_right: #153)
- [v0.8.0](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.8.0) (:arrow_right: #145 )
