### ISSUE TITLE
K3S Automatic upgrade is not working

### ISSUE THREAD

**Issue by bkraegelin** [rancher/system-upgrade-controller#178]
Same situation as issue #90
K3S Automatic upgrade is not working

system-upgrade-controller latest
0.8.1

K3OS v0.21.1-k3s1r0
K3S v1.21.1+k3s1

According to #90
Error Message: sha256sum: can't open '/host/sbin/k3s': No such file or directory

/sbin/k3s is symlink to /k3os/system/k3s/current/k3s

I cannot follow the suggested fix as K3S gets installed automatically from K3OS ISO image. I do not have any idea, how to fix this within the manifest or the upgrade plan. Do we need a fix and a newer release?

**Comment by dweomer** [comment]
k3s-upgrade is not suited to upgrade k3s on a k3os system.
