### ISSUE TITLE
Support for openSuse MicroOS

### ISSUE THREAD

**Issue by bkraegelin** [rancher/system-upgrade-controller#209]
**Is your feature request related to a problem? Please describe.**
K3OS does not get updates anymore. OpenSuse MicroOS seems to be the natural successor.

**Describe the solution you'd like**
Upgrading openSuse MicroOS from within K3S. So I can fully manage my cluster(s) using Rancher UI.

**Describe alternatives you've considered**
Rely on different upgrade mechanisms described by Suse. All of them need additional workflows.

**Additional context**
As K3S upgrades using system-upgrade controller, and K3OS did that too, it seems natural to follow this way.

**Comment by dweomer** [comment]
Is this a problem with SUC or a problem with assumptions baked into https://github.com/k3s-io/k3s-upgrade/blob/a78cfaf2446b8d6b014a76c2812a1349e1738e37/scripts/upgrade.sh ?

Likely more appropriate to bring this up with the k3s project directly: https://github.com/k3s-io/k3s/issues

**Comment by brandond** [comment]
There is an example available at https://github.com/rancher/system-upgrade-controller/blob/master/examples/openSUSE/microos.yaml
