### ISSUE TITLE
(rancher-imported) default plans automatically created?

### ISSUE THREAD

**Issue by strowi** [rancher/system-upgrade-controller#234]
**Version**

0.10.0

**Platform/Architecture**

linux-amd64

**Describe the bug**

Deploying onto a k3s-cluster that is imported into rancher, it seems default-plans are being created at some point: "k3s-master-plan" and "k3s-worker-plan"

```yaml
apiVersion: v1
items:
- apiVersion: upgrade.cattle.io/v1
  kind: Plan
  metadata:
    creationTimestamp: "2023-03-24T12:34:32Z"
    generation: 1
    labels:
      rancher-managed: "true"
    name: k3s-master-plan
    namespace: cattle-system
    resourceVersion: "17428"
    uid: 52a63e52-5a3a-4919-95ef-81e27a4833db
  spec:
    concurrency: 1
    cordon: true
    nodeSelector:
      matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: In
        values:
        - "true"
    serviceAccountName: system-upgrade-controller
    tolerations:
    - operator: Exists
    upgrade:
      image: rancher/k3s-upgrade
    version: v1.24.11+k3s1
- apiVersion: upgrade.cattle.io/v1
  kind: Plan
  metadata:
    creationTimestamp: "2023-03-24T12:34:32Z"
    generation: 1
    labels:
      rancher-managed: "true"
    name: k3s-worker-plan
    namespace: cattle-system
    resourceVersion: "17429"
    uid: 4a06c6fc-7513-4266-8028-9f83631ce1f1
  spec:
    concurrency: 1
    cordon: true
    nodeSelector:
      matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: DoesNotExist
    prepare:
      args:
      - prepare
      - k3s-master-plan
      image: rancher/k3s-upgrade:v1.24.11-k3s1
    serviceAccountName: system-upgrade-controller
    tolerations:
    - operator: Exists
    upgrade:
      image: rancher/k3s-upgrade
    version: v1.24.11+k3s1
```

**To Reproduce**

Create k3s-cluster, import into rancher, apply system-upgrade-controller-manifest (latest).

**Expected behavior**

No automatic upgrade-plans being created.

**Actual behavior**

Above plans being created automatically. Worse - automatically re-created after deletion.

**Additional context**

**Comment by strowi** [comment]
Sorry wrong repo. It seems rancher creates that plan automatically when imported.

**Comment by nflondo** [comment]
Hello @strowi  Did this issue get moved and resolved?  I'm running into the same problem.  Thanks in advance.

**Comment by strowi** [comment]
Hi @nflondo ,

sadly neither nor. My current solution is to deploy these via fleet once, when i want to update our edge-devices, and delete it afterwards. Still a little buggy, but for now it kinda works.
