### ISSUE TITLE
automatic cleanup of upgrade jobs

### ISSUE THREAD

**Issue by dweomer** [rancher/system-upgrade-controller#24]
**Is your feature request related to a problem? Please describe.**
This controller purposely orphans upgrade jobs after they have been scheduled to make reasoning about system state less of a shot-in-the-dark but this can result in jobs and their pods, long since complete, hanging around and polluting `kubectl` output. **We should consider cleaning up stale jobs every so often.**

**Describe the solution you'd like**
Upgrade jobs of a certain age, regardless of the status of plans which were applied, should be cleaned up and removed from the system (this includes their pods). This would probably be most easily accomplished by integrating with the [TTL Controller for Finished Resources](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/)

**Describe alternatives you've considered**
Mark and sweep effected by this controller itself.

**Additional context**
See the `kubectl` output in #23. Pods that incur a reboot as part of the upgrade job will in many cases end up in the `Unknown` state along with a second run of the pod. This may be confusing and shouldn't persist eternally.

**Comment by tobru** [comment]
Good idea! Using the TTL controller could make sense as this doesn't involve any other component which would need to be installed. It certainly would have to be configurable, probably in the Plan spec...

**Comment by cjellick** [comment]
I opened a corresponding issue in rancher for our QA to track: https://github.com/rancher/rancher/issues/25929

**Comment by dweomer** [comment]
Addressed via #48 and #49
