### ISSUE TITLE
Basic Deployment issue

### ISSUE THREAD

**Issue by tamirshkolnik** [rancher/system-upgrade-controller#242]
**Version**
v0.11.0

**Platform/Architecture**
darwin-amd64

**Describe the bug**
After deploying the system-upgrade-controller the pod failed to start. before applying any Plan

**To Reproduce**

**Expected behavior**
expect the pod to run successfully

**Actual behavior**

**Additional context**

![image](https://github.com/rancher/system-upgrade-controller/assets/86972675/6f1b3aa6-5c15-4465-ac01-d776fce49645)

**Comment by brandond** [comment]
It looks like you didn't deploy the CRDs? Please make sure you're also installing the crd.yaml release asset.
