### ISSUE TITLE
`crd.yaml` is not attached to Github release for v0.12.0

### ISSUE THREAD

**Issue by onedr0p** [rancher/system-upgrade-controller#247]
Previous releases of SUC there has been a `crd.yaml` artifact attached to the Github release, it appears missing for v0.12.0.

**Comment by IT-Cru** [comment]
Also other assets are missing if you compare release v0.12.0 and previous one v0.11.0.

Normally they are 21 assets in last previous releases and in v0.12.0 only 7 exists. Also system-upgrade-controller.yaml is missing and all users which requests https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml get a HTTP status 404 currently. So all usages in any CI jobs or automated processes could be broken.

**Comment by hurzelpurzel** [comment]
I ended up at the same problem when using the k3s website link to the manifest. Therefore I switched to v11

**Comment by onedr0p** [comment]
Sorry to be a bit of a bother but it kind of sucks how painful this project is to deploy... no Helm chart, barely functional kustomize support, no way to install CRDs separately outside using the Github release artifact (which is currently broken).

It would be nice to have a clearer automated way to install and manage updates to this but it doesn't look like it will get the love it needs to make that happen.

**Comment by hurzelpurzel** [comment]
Checked the scripts subfolder. All the build stuff is located there. I found that the AMD64 build hasn't been run for v.12.0 and that is reason for the missing CRD.

**Comment by hurzelpurzel** [comment]
> Sorry to be a bit of a bother but it kind of sucks how painful this project is to deploy... no Helm chart, barely functional kustomize support, no way to install CRDs separately outside using the Github release artifact (which is currently broken).
> 
> It would be nice to have a standard/cleaner automated way to install and manage updates to this outside of `kubectl apply -f https://...` but it doesn't look like it will get the love it needs to make that happen.
> 
> I don't mean to come off rude or anything, just hopefully giving some constructive criticism that may help make things better.

Added a helm chart in PR  #248

**Comment by onedr0p** [comment]
@brandond any thoughts here?

**Comment by brandond** [comment]
Tag CI failed, for reasons that do not appear to be related to anything that was changed in this release. I'll re-run it and see if it completes successfully.

**Comment by brandond** [comment]
It looks like something changed in the CI environment, we'll have to fix that and cut a new tag.

**Comment by onedr0p** [comment]
Any update here?

**Comment by onedr0p** [comment]
Looks like this was fixed. Thanks!
