### ISSUE TITLE
v0.12.0 release for linux/amd64 or linux/arm64

### ISSUE THREAD

**Issue by tamirshkolnik** [rancher/system-upgrade-controller#249]
Is there an estimate of when versions will be released for linux/amd64 or linux/arm64 ?

And why there is only s390X release for now?

**Comment by hurzelpurzel** [comment]
After disabling Buildkit the build works. See PR #248

**Comment by tamirshkolnik** [comment]
@hurzelpurzel What does it mean? where can I find an image for  Linux/amd64 or Linux/arm64 ?

should I build it by myself?

**Comment by hurzelpurzel** [comment]
I just want to inform you, that I create a Pull Request for a helm chart and that triggered automatically a test build, that pass the build process in Drone after dieabling the "Buildkit" flag in the buildscripts. I'm not able to fix the release but I think the build failure is caused  by a change in the build container that results in an missing docker component. I just want to share that, but I think we all have to wait until the maintainers will fix the release. Sorry.

**Comment by onedr0p** [comment]
This can be closed v0.13.0 was released
