### ISSUE TITLE
Many logs stating "error syncing" DesiredSet - Replace Wait batch/v1, Kind=Job 

### ISSUE THREAD

**Issue by tobru** [rancher/system-upgrade-controller#25]
**Version**

0.2.0

**Describe the bug**

The following lines are logged many times during Plan execution:

```
E0206 21:05:57.849250       1 controller.go:135] error syncing 'system-upgrade/ubuntu-latest': handler system-upgrade-controller: DesiredSet - Replace Wait batch/v1, Kind=Job system-upgrade/upgrade-node-10-with-ubuntu-latest-at-cea9cf1a0a721c805e3-42e4b for system-upgrade-controller system-upgrade/ubuntu-latest, requeuing
```

**To Reproduce**

There is nothing special to do to replicate it, happens during normal Plan operations.

**Expected behavior**

Either no such messages are logged if they are not an issue or the issue is solved.

**Comment by daxmc99** [comment]
Also seeing this
