### ISSUE TITLE
Bump API version

### ISSUE THREAD

**Issue by AndreiBarbuOz** [rancher/system-upgrade-controller#254]
**Is your feature request related to a problem? Please describe.**
We want to import the `github.com/rancher/system-upgrade-controller/pkg/apis` package from `github.com/rancher/system-upgrade-controller` module to use the typed client
The import is causing conflicts though, because the imported `k8s.io/api` version is too old
https://github.com/rancher/system-upgrade-controller/blob/23f7fe005b44f3bdea1a65bbc83bef40060d4ef7/pkg/apis/go.mod#L8

**Describe the solution you'd like**
Bump the version. It looks like the project is active

**Comment by dweomer** [comment]
a `replace` in the `go.mod` doesn't solve this for you?

**Comment by AndreiBarbuOz** [comment]
hey @dweomer, 

do you mean replace `k8s.io/api => k8s.io/api v0.25.2`? 

we have such a directive already, 
the failure come from the import of deprecated APIs by the version used by the SUC submodule, which are no longer found in newer versions of the imported `k8s.io/api` package

**Comment by brandond** [comment]
Done in https://github.com/rancher/system-upgrade-controller/pull/255
