### ISSUE TITLE
Ability to customize / add scripts 

### ISSUE THREAD

**Issue by HoustonDad** [rancher/system-upgrade-controller#270]
**Is your feature request related to a problem? Please describe.**
Upgrading from 1.24 to 1.25 requires a lot of changes. When dealing with a major amount of clusters, it would be beneficial to be able to adjust or add upgrade scripts that the system-upgrade-controller runs

An example of this, would be a customer who wants to have a custom PSP -> PSA converter ran during a run of the system-upgrade-controller, or if they want to change values in a config.yaml during upgrade, like updating the profile key for the new CIS Benchmark versions

**Describe the solution you'd like**
The ability to drop in scripts or overwrite scripts that the system-upgrade-controller runs so users can customize them to their infrastructure.

**Comment by brandond** [comment]
The system-upgrade-controller does whatever the plan says. If you want it to run additional steps as part of the upgrade, you should include those in your plan. The upgrade controller itself has no knowledge of what the plans are doing, or even what the affected versions are. It just runs the images in the configured order.
