### ISSUE TITLE
system-upgrade-controller: failed to create job for hostname which has uppercase letters

### ISSUE THREAD

**Issue by GayathriBandaru94** [rancher/system-upgrade-controller#273]
**Version**
v0.11.0

**Platform/Architecture**
linux-amd64

**Describe the bug**
For certain hostnames, the controller fails to create the update job. Because metadata.name becomes an invalid value, means the job name does not match the regex used for validation the name, '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'

**To Reproduce**
Enable upgrade on a host that has the hostname like this **k8s-master00000E** and the plan name server-plan

**Expected behavior**
The controller should upgrade the nodes irrespective of the case of the hostname

**Additional context**
The error message is below, seems like the controller takes the name of the host as is with uppercase letters.

```bash
time="2023-11-13T10:37:58Z" level=error msg="error syncing 'system-upgrade/server-plan': handler system-upgrade-controller: failed to create system-upgrade/apply-server-plan-on-k8s-master00000E-with-08d96dc0f367bf-3271c batch/v1, Kind=Job for system-upgrade-controller system-upgrade/server-plan: Job.batch \"apply-server-plan-on-k8s-master00000E-with-08d96dc0f367bf-3271c\" is invalid: metadata.name: Invalid value: \"apply-server-plan-on-k8s-master00000E-with-08d96dc0f367bf-3271c\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing"
```

**Comment by brandond** [comment]
What version of Kubernetes are you using? How are you setting the node names? Can you show the output of `kubectl get node -o wide` on your cluster? I am not sure I have ever seen nodes with uppercase names; I honestly didn't expect Kubernetes to allow this.

**Comment by GayathriBandaru94** [comment]
Hello @brandond 

My Kubernetes version is v1.27.7. The node names are being generated by azure vmss itself. 

<img width="1208" alt="Capture" src="https://github.com/rancher/system-upgrade-controller/assets/147155202/309e4e98-2a85-4f39-a689-b150405e3093">

And the controller is picking up the hostname which has uppercase alphabet and throwing the error as mentioned previously.

**Comment by brandond** [comment]
ah that is interesting. I'm not sure why we would be using the hostname label instead of the node name.

**Comment by brandond** [comment]
Oh this is on me 🙃 https://github.com/rancher/system-upgrade-controller/pull/150
