### ISSUE TITLE
Initial job always fails for every node

### ISSUE THREAD

**Issue by GayathriBandaru94** [rancher/system-upgrade-controller#275]
**Version**
v0.11.0

**Platform/Architecture**
linux-amd64

**Describe the bug**
For every node after applying the plan the first job which is created is failing and the second job helps to upgrade the node.

**To Reproduce**
Enable upgrade with the first job itself.

**Additional context**
Attaching the errors below

<img width="1235" alt="Capture" src="https://github.com/rancher/system-upgrade-controller/assets/147155202/e280418d-a1e5-4761-a407-d9b30301ed59">
<img width="1904" alt="server-plan_1" src="https://github.com/rancher/system-upgrade-controller/assets/147155202/3f1ea4cb-7b5e-48e3-91dc-30ced127280b">

**Comment by brandond** [comment]
You didn't attach any logs from either the controller or the job pods. All you've provided is a screenshot of an error that says it failed to read logs from the selected pod. Can your get the actual logs from any of the involved components?

**Comment by GayathriBandaru94** [comment]
Hello @brandond 

Please find below the screen shots of logs of the jobs, job pods and the controller.

1. Initial jobs created for server and agent plans

<img width="1245" alt="1" src="https://github.com/rancher/system-upgrade-controller/assets/147155202/2d2bc518-f51b-454f-a1ba-8d2952e2a452">

2. Containers inside the initial job for master plan

<img width="1248" alt="2" src="https://github.com/rancher/system-upgrade-controller/assets/147155202/8431aae2-aa54-4275-8e90-1ec69063bf51">

3. Logs of pods of the initial job for masterplan

<img width="1050" alt="3" src="https://github.com/rancher/system-upgrade-controller/assets/147155202/83805c27-94c9-4263-a4f7-71263d2c2792">

4. Logs of the upgrade controller

<img width="1047" alt="4" src="https://github.com/rancher/system-upgrade-controller/assets/147155202/55bd7e72-1151-4bf3-95b6-b7c40b0beb4f">

**Comment by brandond** [comment]
Can you provide any information - logs, status, or so on - from the failed pods or job? I'm still not seeing what's actually going wrong here.

**Comment by teknologista** [comment]
same here going from k3s v1.28.3+k3s2 to v1.28.4+k3s2 with concurrency 1

for each job:

first job instance runs prepare+drain and fails at upgrade container, the relaunches and succeeds

every job runs twice (2 instances of same node job), first run shows failed and subsequent one shows Completed.

Once everything completes all nodes are upgraded succesfully

settings on agent nodes:
  drain:
    force: true
    skipWaitForDeleteTimeout: 60 # 1.18+ (honor pod disruption budgets up to 60 seconds per pod then moves on)
    disableEviction: true

**Comment by brandond** [comment]
> first job instance runs prepare+drain and fails at upgrade container, the relaunches and succeeds

Can you provide logs showing why it fails at the upgrade container?

**Comment by brandond** [comment]
That was what I was seeing as well. I'm going to close this out; if you can provide evidence that this isn't working as designed then we can reopen.
