### ISSUE TITLE
Need a new release after #273 issue is fixed

### ISSUE THREAD

**Issue by GayathriBandaru94** [rancher/system-upgrade-controller#276]
**Is your feature request related to a problem? Please describe.**
With the #273 issue fix, when I use the following command to install the controller I still get the same error. The last release was [v0.13.1] published in August.

```bash
kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
```

**Describe the solution you'd like**
I would like to install the controller with the modified code. May be a new release would be helpful.

**Comment by brandond** [comment]
v1.13.2 has been tagged.
