### ISSUE TITLE
rancher/rke2-upgrade does not have ARM64 arch available (nor RISCV64)

### ISSUE THREAD

**Issue by pascal71** [rancher/system-upgrade-controller#280]
**Version**
v0.13.2

**Platform/Architecture**

Linux/ARM64

**Describe the bug**
pascal@rpb58-n01:~/upgrade$ kubectl get pods -n system-upgrade
NAME                                                              READY   STATUS                  RESTARTS   AGE
apply-agent-plan-on-rock5b-n11-with-7a66eb76bafdd1dfeb6e1-hjd4j   0/1     Init:ImagePullBackOff   0          8m55s
apply-agent-plan-on-rock5b-n12-with-7a66eb76bafdd1dfeb6e1-mm5rd   0/1     Init:ImagePullBackOff   0          8m54s
apply-server-plan-on-rpb58-n01-with-7a66eb76bafdd1dfeb6e1-hdxtf   0/1     ImagePullBackOff        0          8m55s
system-upgrade-controller-56d9f7c4f5-vj6gg                        1/1     Running                 0          15m

And a POD describe:

Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m50s                   default-scheduler  Successfully assigned system-upgrade/apply-agent-plan-on-rock5b-n11-with-7a66eb76bafdd1dfeb6e1-hjd4j to rock5b-n11
  Normal   Pulling    8m5s (x4 over 9m49s)    kubelet            Pulling image "rancher/rke2-upgrade:v1.28.1-rke2r1"
  Warning  Failed     8m2s (x4 over 9m45s)    kubelet            Failed to pull image "rancher/rke2-upgrade:v1.28.1-rke2r1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rke2-upgrade:v1.28.1-rke2r1": no match for platform in manifest: not found
  Warning  Failed     8m2s (x4 over 9m45s)    kubelet            Error: ErrImagePull
  Warning  Failed     7m47s (x6 over 9m45s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m41s (x20 over 9m45s)  kubelet            Back-off pulling image "rancher/rke2-upgrade:v1.28.1-rke2r1"

**To Reproduce**
Install RKE2 server on Raspberry PI5, RKE2 release 1.27.8
Create upgrade plan to v1.28.1-rke2r1

**Expected behavior**
Upgrade succeeds

**Actual behavior**
Upgrade controller is not able to pull an rancher/rke2-upgrade:v1.28.1-rke2r1 image that has the ARM64 part in it

**Additional context**

If you need any help; kindly let me know.
If I can build the container myself for tests, kindly let me know where I can find the instructions

**Comment by brandond** [comment]
arm64 support for rke2 is still experimental, and not all components are available for that architecture yet.

riscv64 support is not currently planned.
