### ISSUE TITLE
getting warning installing controller

### ISSUE THREAD

**Issue by tim-oe** [rancher/system-upgrade-controller#299]
**Version**

controller: 
0.13.4

kube:
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6+k3s1

**Platform/Architecture**

Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-1047-raspi aarch64)
**Describe the bug**
running:
`kubectl apply -f https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml`

getting following warning:
Warning: resource namespaces/system-upgrade is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.

**To Reproduce**

`kubectl apply -f https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml`

**Expected behavior**

shouldn't get warning, needed annotation should be applied

**Actual behavior**

getting warning above

**Additional context**

**Comment by brandond** [comment]
The warning is from kubectl, and indicates that you used some too other than `kubectl apply` to initially create them. This is not an issue with the SUC.
