### ISSUE TITLE
When to expect a new release?

### ISSUE THREAD

**Issue by harsimranmaan** [rancher/system-upgrade-controller#314]
There are some public golang CVEs that requires addressing in the suc. Per the security policy, these are patched during the dev cycle. Is there a cadence to expect such patch releases?

**Comment by brandond** [comment]
There are a couple packaging issues I want to fix before we do another release. It is on my radar for sometime in the next week or two.

**Comment by buroa** [comment]
@brandond Any updates?

**Comment by harsimranmaan** [comment]
Hi team, it would great if a new release could be published as suc gets flagged for multiple critical vulns. The patches have been merged already,

**Comment by kashalls** [comment]
@brandond Do you need any help to get this moving?

**Comment by brandond** [comment]
Sorry, there was a bunch of release CI stuff to fix - the changes from https://github.com/rancher/system-upgrade-controller/pull/311 did not actually work to move publish CI over to GHA.

[v0.14.0](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.14.0) should work.

**Comment by harsimranmaan** [comment]
Thanks Brandon but could the release be bumped to v0.15.0? 0.14.0 was likely published in the past and recalled it seems as gosumdb already has entries for it with a different shasum. Please see https://pkg.go.dev/github.com/rancher/system-upgrade-controller?tab=versions

**Comment by brandond** [comment]
I'm not able to find any references to that tag on GH or Docker Hub, so I have no idea where that would have come from. I can tag 0.15.0 next week when I am back in the office.
