### ISSUE TITLE
Allow priorityClassName in the PodTemplateSpec of the Jobs created by an upgrade plan

### ISSUE THREAD

**Issue by fretb** [rancher/system-upgrade-controller#333]
Nodes with the [CriticalAddonsOnly taint](https://docs.rke2.io/install/ha#2a-optional-consider-server-node-taints) only allow pods to be ran that have a certain [priorityClassName](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/).

The [PodTemplate created by the upgrade plans](https://github.com/rancher/system-upgrade-controller/blob/f7f79ff18733b3c67ef0860db635abcf2391430f/pkg/upgrade/job/job.go#L268), however, does not allow this to be set.

This results in the upgrade pods staying in `Pending` phase on nodes that have the taint. We now temporarily removed the taint on such nodes to allow the upgrade to succeed.

It would be nice to allow `priorityClassName` to be set to a value in the upgrade plan manifest.

**Comment by brandond** [comment]
> @fretb 
> Nodes with the CriticalAddonsOnly taint only allow pods to be ran that have a certain priorityClassName

That is not how taints work. Taints require matching Tolerations, not priorityClassName. As @glennpratt noted, you can already add tolerations to the plan.

**Comment by fretb** [comment]
Thank you! Sorry for the noise.
