### ISSUE TITLE
Nil pointer exception when there is no upgrade field

### ISSUE THREAD

**Issue by rmweir** [rancher/system-upgrade-controller#35]
**Version**

0.2.0

**Platform/Architecture**

linux amd64
**Describe the bug**

bug

**To Reproduce**

apply a plan without an upgrade field

**Expected behavior**

a message indicating it is a no op, or that upgrade is blank

**Actual behavior**

nil pointer exception

**Comment by dweomer** [comment]
Yeah, this definitely needs to be validated. A plan missing an `upgrade` container isn't super useful.

**Comment by dweomer** [comment]
The issue here is that a Plan with `.spec.upgrade` == `nil` is malformed and should be rejected by the api-server. This will require and updated schema. It would be nice if there was a struct annotation that we could use (possibly in the norman project?) to indicate a required field.

**Comment by dweomer** [comment]
As per @ibuildthecloud, a `wrangler:"required"` tag ought to do it.

**Comment by ShylajaDevadiga** [comment]
Verified missing upgrade image, errors out with 
```Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
