### ISSUE TITLE
support tolerations for Plans

### ISSUE THREAD

**Issue by billimek** [rancher/system-upgrade-controller#55]
**Is your feature request related to a problem? Please describe.**

As an operator of a mixed-architecture kubernetes cluster, I rely on node taints to control scheduling of workloads to arm (arm64) based nodes (the reason for this is that there are still a lot of things that don't support arm/arm64).  I leverage tolerations to control scheduling of 'safe' workloads that will actually run on arm-based nodes.

**Describe the solution you'd like**

I want the ability to specify node tolerations when defining system-upgrade-controller Plan(s),
so that I can upgrade my arm/arm64 based k3s nodes.

**Describe alternatives you've considered**

I tried adding tolerations to the `system-upgrade-controller` Deployment spec in hopes that the associated upgrade jobs created based on the Plans would somehow inherit this toleration, but they did not.

**Comment by dweomer** [comment]
@billimek what version of kubernetes are you running on? are neither `beta.kubernetes.io/arch` nor `kubernetes.io/arch` available to match against accordingly in `nodeSelector` for your **Plan**(s)?

I gather what you are asking for is that, to account for your not unreasonable setup (aka node taints based on arch), you need to have tolerations placed on the pods that belong to the upgrade jobs (that are generated when applying a Plan). And you need this at plan granularity, is that right? Or would at controller granularity suffice (controllers are namespaced which means that it would be a natural place to specify defaults for plans)?

---

I find myself wishing [Pod Presets](https://kubernetes.io/docs/tasks/inject-data-application/podpreset/) accounted for tolerations.

**Comment by billimek** [comment]
@dweomer I'm running k8s `v1.17.4+k3s`).  The labels you mention are indeed available to select for the Plan's nodeSelector, but I wonder if specifying that would work due to the node taints?

Regarding the ability to specify tolerations, I don't believe it needs to be at Plan granularity, but suspect some others may find that useful.  Personally, controller granularity work work just as well.  By that I mean that if a controller is defined to work with tolerations and the associated pods created by the plans also inherit the tolerations applied to the controller.

**Comment by David-Igou** [comment]
I ran into this issue this week on my hybrid x86/arm cluster, where the only way I could get upgrade pods to schedule was remove my taints. I didn't seem to find any other way to account for this in the plan cr. Is this currently a limitation of the project, or is there a better way I could have gone about this?
I deployed the controller via rancher-server running on the same cluster

**Comment by dweomer** [comment]
I think architecture-specific taints (any arbitrary taints, actually) are an anti-pattern but I understand why folks use them. I’ve got an idea for a fix and have this slated for the next milestone. Hopefully will have it in a milestone build next week.
