### ISSUE TITLE
system-upgrade-controller CrashLoopBackOff

### ISSUE THREAD

**Issue by mcanevet** [rancher/system-upgrade-controller#56]
**Version**
0.4.0

**Platform/Architecture**
rpi3 (armv7)

**Describe the bug**
Following this doc: https://rancher.com/docs/k3s/latest/en/upgrades/automated/#install-the-system-upgrade-controller I get CrashLoopBackOff on system-upgrade-controller pod.
Pod logs:
```
W0328 06:42:10.648220       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-03-28T06:42:11Z" level=fatal msg="Error starting: Get https://10.43.0.1:443/api/v1/namespaces/kube-system: dial tcp 10.43.0.1:443: connect: connection refused"
```

**Comment by dweomer** [comment]
This looks like a problem with your k3s (assuming you are using k3s?) installation: if the apiserver isn't accepting connections there isn't much SUC can do.

That said, I am seeing some apparent networking breakage (via reported issues on the newest release) with the recent release of k3s. Do you get the same behavior with [v1.17.3+k3s1](https://github.com/rancher/k3s/releases/tag/v1.17.3%2Bk3s1)?

**Comment by mcanevet** [comment]
OK, I reinstalled it from scratch and it works now.
