### ISSUE TITLE
Can't find Plan CRD

### ISSUE THREAD

**Issue by faheem556** [rancher/system-upgrade-controller#66]
I can't find *Plan* CustomResourceDefinition object in the manifests folder. Installation fails on an RKE cluster with the object not found error for *Plan* CRD.

**Comment by dweomer** [comment]
@faheem556 the CRD is registered by the controller at start-up. Also, the controller will not concern itself with anything outside of the namespace it is running in (other than nodes).

**Comment by faheem556** [comment]
That was it. Thank you @dweomer !
