### ISSUE TITLE
Upgrade fails on k3s high availability with embedded db

### ISSUE THREAD

**Issue by e3b0c442** [rancher/system-upgrade-controller#91]
**Version**
v0.5.0

**Platform/Architecture**
linux-arm64

**Describe the bug**
system-upgrade-controller fails to upgrade a node that was the initial node in a high-availability cluster with embedded database started using the `--cluster-init` option as described in the docs

**To Reproduce**
1. Start a new high availability k3s cluster using the `--cluster-init` flag
2. Add `system-upgrade-controller` and add a server plan

**Expected behavior**
k3s is upgraded as expected

**Actual behavior**
`apply-server-plan` fails with the following output:
```
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver)'
+ awk '{print $1}'
+ K3S_PID=
+ '[' -z  ]
+ fatal 'K3s is not running on this server'
+ echo '[ERROR] ' 'K3s is not running on this server'
[ERROR]  K3s is not running on this server
+ exit 1
```

**Additional context**
Running through the bash script step by step I found that the issue lies with `grep -E -v '(init|grep|channelserver)'`, which matches `init` in `--cluster-init`. This removes the k3s pid from the list causing the script to find no PID.

**Comment by e3b0c442** [comment]
It looks like the root cause of this may actually lie in rancher/k3s-upgrade.

**Comment by viceice** [comment]
any chances to get this fixed? how to cancel the hung upgrade?

**Comment by engineer11111** [comment]
Hey guys, any chance to get it fixed ?
It would be great if you can look into the PR which supposedly removes that problem https://github.com/k3s-io/k3s-upgrade/pull/24.
Thank you :)

**Comment by brandond** [comment]
I thought this was fixed in https://github.com/k3s-io/k3s-upgrade/pull/17

**Comment by e3b0c442** [comment]
Unfortunately not, the issue is that the grep in the script is filtering `init` which also captures `cluster-init`, as demonstrated (and fixed) on that PR.
