### ISSUE TITLE
Support Common Tolerations in Deployment

### ISSUE THREAD

**Issue by MonzElmasry** [rancher/system-upgrade-controller#95]
Added tolerations for "CriticalAddonsOnly" and "node-role.kubernetes.io/master".
The Deployment has nodeAffinity to "node-role.kubernetes.io/master", but has no tolerations.
If the master node is tainted, the Pod cannot be scheduled and stays in Pending.

**Comment by MonzElmasry** [comment]
fixed via https://github.com/rancher/system-upgrade-controller/pull/84

**Comment by ShylajaDevadiga** [comment]
Reproduced the issue with earlier SUC versions and verified with SUC v0.6.1, with master node tainted, SUC Pod was schedulable and in Running state
